blacklist_file = "exclude.conf"
worker_count = 100
timeout_ms = 5000
worker_recheck = 0
recheck_resync_delay = 10000
db_url = "host=127.0.0.1 port=5432 user=mc_scanner password=mc_scanner dbname=mc_scanner"
