ip_range = "45.135.194.24/10"
masscan_rate = 10000
isp_scan_enabled = true
mc_checker_threads = 50
database_url = "host=127.0.0.1 port=5555 user=mc_scanner password=K2306luna? dbname=mc_scanner"
timeout_ms = 6000
blacklist_file = "exclude.conf"
masscan_use_sudo = true
