blacklist_file = "exclude.conf"
timeout_ms = 2500
db_url = "host=127.0.0.1 port=5555 user=mc_scanner password=pwd dbname=mc_scanner"
enable_isp_scan = true
isp_scan_subnet = 24
extended_port_scan = true
worker_count = 1000
batch_size = 1000
concurrency_per_worker = 10
